# Generated by Django 3.2.20 on 2023-11-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_myprojects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
