# Generated by Django 3.2.20 on 2023-11-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_myprojects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
